### ISSUE TITLE
Request to remove dependency on fluttertoast

### ISSUE THREAD

**Issue by scottTomaszewski** [jhomlala/catcher#107]
I have the need to deploy a flutter web app to an environment without internet.  The fluttertoast (https://pub.dev/packages/fluttertoast) web implementation uses toastify (https://github.com/apvarun/toastify-js) which is requested at runtime and fails to load.  

Can you replace this dependency with another?  

Thanks!

**Comment by jhomlala** [comment]
Hi Scott,
can you report this issue to the author of fluttertoast? I don't want to remove fluttertoast just only because it doesn't work on web right now correctly. 

Anyway I've prepared for you branch without fluttertoast. Just use this in your project:
```
catcher:
  git:
    url: https://github.com/jhomlala/catcher
    ref: feature/removed_toast_handler
```

Cheers,
Jakub
