### ISSUE TITLE
Support Flutter Web

### ISSUE THREAD

**Issue by wverhoeven** [jhomlala/catcher#87]
This package would be incredibly useful for Flutter Web. Are there any plans to support it?

**Comment by jhomlala** [comment]
Yes, but it will require a lot of refactoring.

**Comment by joe-getcouragenow** [comment]
i was just about to make the same issue :)

Can you outline the architectural blockers for making it work with flutter web.
SO then me and others can help

**Comment by jhomlala** [comment]
Catcher has now support for web. It's not released yet, but you can try it:
```
  catcher:
    git:
      url: https://github.com/jhomlala/catcher
      ref: feature/web_support
```

Some features are missing for web. Please read readme from here before starting: https://github.com/jhomlala/catcher/blob/feature/web_support/README.md

Waiting for your feedback.
@joe-getcouragenow @wverhoeven
